### ISSUE TITLE
"issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by sato-taku** [sato-taku/sameshi#26]
### 概要
"issueベースの開発"
各機能実装に伴うissueの作成

### 実装予定の機能
- [x] ユーザー登録機能
- [x] ログイン・ログアウト機能
- [x] 新規投稿
- [x] 投稿一覧（Google Maps APIによるマップ上にマーカーで投稿表示）
- [x] 検索（フリーワード・サウナ施設名・サ飯メニュージャンルでの複数検索）
- [x] 投稿詳細
- [x] マイページ
- [x] お気に入り機能
- [x] SNSシェア機能

### 必要なページ
- [x] トップページ
- [x] ログインフォーム
- [x] 新規登録フォーム
- [x] 投稿一覧ページ
- [x] 投稿詳細ページ
- [x] 現在地から探すページ
- [x] 投稿フォーム
- [x] マイページ
- [x] 利用規約ページ
- [x] プライバシーポリシーページ
- [x] パスワードリセットページ
- [x] パスワードリセット用メール

**Comment by takyyk** [comment]
プロジェクトボードも是非作成してみてください！

**Comment by sato-taku** [comment]
@takyyk 

お忙しい中ありがとうございます！

プロジェクトボードを作成するとはどういうことか確認したいのですが、
リポジトリとプロジェクトが繋がっていないようでしたので
リポジトリ側のプロジェクトから **Link a project** で選択し紐付けしました。

もし意味が違うようでしたらどういう意味か教えていただきたいです！

**Comment by Tsuchiya2** [comment]
ストーリーポイントが振られていないものがあるので、ポイント付をお願いします。

また、5ポイント付いているものは1,2になるくらい細分化しましょう。

**Comment by sato-taku** [comment]
@Tsuchiya2 
お忙しい中対応ありがとうございます！

おっしゃる通りで、
実装イメージがついていないもののストーリーポイントを多く見積もっていました。
細分化してみたのですが、確認いただけるとありがたいです。
よろしくお願いいたします！

**Comment by tarakish** [comment]
細分化することで明確になっているように見受けられました。LGTMです！
実装頑張ってください！

**Comment by sato-taku** [comment]
@tarakish 
ありがとうございます！！
