### ISSUE TITLE
MVPリリース

### ISSUE THREAD

**Issue by sato-taku** [sato-taku/sameshi#71]
## 各種情報
サービス名
**サ飯の時間**
サービスURL
https://sameshi.fly.dev/

## READMEレビュー時にMVPリリース時点で実装予定だった機能
**実装済み**
- [x] ユーザー登録機能
- [x] ログイン・ログアウト機能
- [x] 投稿作成
- [x] 投稿一覧
- [x] 投稿詳細
- [x] 検索機能
- [x] マイページ
- [x] お気に入り機能
- [x] SNSシェア機能
- [x] パスワードリセット機能
- [x] パスワードリセットメール 

## READMEレビュー時から変更した機能
- [x] オートコンプリート機能（投稿作成 / サウナ施設入力フォーム）
- [x] プレビュー表示機能（投稿作成 / 投稿画像）

## サービスイメージがわかるようなスクリーンショット等
投稿作成画面
[![Image from Gyazo](https://i.gyazo.com/3e28ac4b5342b0001b5a613b82fdf1ec.gif)](https://gyazo.com/3e28ac4b5342b0001b5a613b82fdf1ec)

投稿一覧画面
[![Image from Gyazo](https://i.gyazo.com/c08525e9b8f3a357e3211fd5d702403a.gif)](https://gyazo.com/c08525e9b8f3a357e3211fd5d702403a)

マップ表示画面
[![Image from Gyazo](https://i.gyazo.com/065889546ff55a08cddf7bf79a0c99c0.gif)](https://gyazo.com/065889546ff55a08cddf7bf79a0c99c0)

投稿詳細画面
[![Image from Gyazo](https://i.gyazo.com/5eb5b1878a195c66d9b09eb729682d5f.gif)](https://gyazo.com/5eb5b1878a195c66d9b09eb729682d5f)

トップページ
[![Image from Gyazo](https://i.gyazo.com/3a7e86974dcb523f16739ba451dc66e9.gif)](https://gyazo.com/3a7e86974dcb523f16739ba451dc66e9)

マイページ
[![Image from Gyazo](https://i.gyazo.com/68282ba4e5386675f8468fdae15b025f.gif)](https://gyazo.com/68282ba4e5386675f8468fdae15b025f)

**Comment by Tsuchiya2** [comment]
機能確認が取れました。LGTMです！
引き続き本リリースに向けて開発頑張ってください。
