### ISSUE TITLE
中間報告レビュー

### ISSUE THREAD

**Issue by tmtkzk0823** [sato-taku/sameshi#92]
@sato-taku 
# 中間報告レビュー

Webアプリの中間報告ありがとうございました！
以下、レビュー内容になりますのでご確認ください。

### 技術
- 所々`.DS_Store`のファイルが存在するので、削除しておくといいと思いまいした。（こちらのファイルは基本的に不要ですが、ディレクトリやファイルを作成したときに、たまに自動で作成されてしまうので気づいた段階で削除してしまって大丈夫です。）
- あとは、以前渡したタスクを基準に実装して頂ければ技術面のアピールは問題ないかと思いました。
- （余裕があれば独自ドメインをとっておくと、アプリの見栄えはよくなるかと思います！）

### ユーザビリティ
- ページネーションにデザインが当たっていなく、どのページを表示しているのかわからなかったので、デザインを当てて、どのページにいるか分かりやすくしてあげるといいと思いました。
- ケバブメニューの中に画像赤枠と同じページ遷移する要素を加えてあげると良さそうです。理由としては、ユーザーの先入観的に、「ケバブメニュー（ハンバーガーメニュー等）には、メイン機能への導線がある」という考えがあるかと思うので、アプリの下部に加えて、ケバブメニューの中にも、表示してあげましょう。

[![Image from Gyazo](https://t.gyazo.com/teams/startup-technology/deee872f03b92eedc7550822170dfe28.png)](https://startup-technology.gyazo.com/deee872f03b92eedc7550822170dfe28)

以上です！
全体的に良くできていて、綺麗なアプリケーションだと思いました！

また上記レビューに関して、質問などありましたらスレッドに記載いただいてご連絡ください！

本リリースまでもう少し！
頑張っていきましょう！

**Comment by sato-taku** [comment]
@tmtkzk0823 

レビューありがとうございます！

- [x] `.DS_store`の削除
- [ ] ページネーションデザイン
- [ ] ケバブメニューにも機能追加
- [ ] 独自ドメインの取得と設定

ページネーションについての視点が特に足りていなかったと感じました！
ご指摘ありがたいです！

全てやるべきだなと思いました。よろしくお願いいたします！
